### ISSUE TITLE
Bulk update

### ISSUE THREAD

**Issue by bnjbvr** [cozy/cozy-data-system#126]
I see there is an end-point for bulk delete, but not for bulk update. However, the db_remove_helper suggests that it shouldn't be too different to do (as a deletion seems to be actually an update, iiuc). Is there any way we could have a bulk update end-point, please?

Here's an API i imagine:
```
PUT /request/:type/:req_name/update
Param:
  type: the doctype name
  req_name: the name of the request
  Body {
    key: only returns document for this key
    keys: [only returns document for this array of keys]
    limit: number of documents to return
    skip: number of documents to skip
    startKey: only returns document after this key
    endKey: only returns document before this key
    update: [[key, value], [key, value]] or [key, value]
  }
  The body is fully optional.
```

For instance, with
```
body = {
  update: ['date', '1234']
}
```
Then the 'date' field of all values should be updated to '1234'.

```
body = {
  update: [['date', '1234'], ['bankAccount', '4321']]
}
```
Then the 'date' field of all values is updated to 1234, and the 'bankAccount' field of all values is updated to 4321.

Not sure about the naming of `update`, maybe `values` or `replaceBy` would be more adequate.
